# -------------------------------------------------------------------
# Purpose:
#   Render Traefik dynamic configuration templates to the stack's
#   dynamic directory.
# -------------------------------------------------------------------

- name: Render Traefik dynamic configs
  template:
    src: "dynamic/{{ item }}.yml.j2"
    dest: "{{ docker_stack.directories.dynamic.path }}/{{ item }}.yml"
    mode: '0644'
  loop:
    - http
    - tcp
    - udp
    - tls
